module CohomologyClassifyingSpacesPseudogroupStructuresTheoremCanonicalLaneLean where

open Lean

/-!
# Root module for CohomologyClassifyingSpacesPseudogroupStructuresTheoremCanonicalLaneLean
-/

import CohomologyClassifyingSpacesPseudogroupStructuresTheoremCanonicalLaneLean.AdmissibleClass
import CohomologyClassifyingSpacesPseudogroupStructuresTheoremCanonicalLaneLean.BridgeLemmas
import CohomologyClassifyingSpacesPseudogroupStructuresTheoremCanonicalLaneLean.GateLemmas
import CohomologyClassifyingSpacesPseudogroupStructuresTheoremCanonicalLaneLean.FinalTheorem
import CohomologyClassifyingSpacesPseudogroupStructuresTheoremCanonicalLaneLean.PseudogroupStructureLayer
import CohomologyClassifyingSpacesPseudogroupStructuresTheoremCanonicalLaneLean.ClassifyingSpaceLayer
import CohomologyClassifyingSpacesPseudogroupStructuresTheoremCanonicalLaneLean.CohomologyLayer