import cohomology_classifying_spaces_pseudogroup_structures_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace cohomology_classifying_spaces_pseudogroup_structures_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end cohomology_classifying_spaces_pseudogroup_structures_theorem_canonical_lane_mathlib
end HautevilleHouse
